"""create vm_requests table

Revision ID: 4fd02f10d03c
Revises: 
Create Date: 2026-06-15 14:21:43.039942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd02f10d03c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vm_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('requester', sa.String(), nullable=False),
    sa.Column('template', sa.Enum('LINUX_ADMIN', 'DEV_WEB', 'DATA_SCIENCE', 'CYBERSEC', name='coursetemplate'), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'RUNNING', 'DESTROYED', name='requeststatus'), nullable=True),
    sa.Column('vm_ip', sa.String(), nullable=True),
    sa.Column('vm_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('validated_by', sa.String(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vm_requests')
    # ### end Alembic commands ###
