---
- name: Mise à jour des paquets
  apt: { update_cache: yes }

- name: Installation Python + Jupyter
  apt:
    name: [python3, python3-pip, python3-venv, git, vim]
    state: present

- name: Installation librairies Data Science
  pip:
    name: [numpy, pandas, scikit-learn, matplotlib, seaborn, jupyterlab]
    executable: pip3
