---
- name: Mise à jour des paquets
  apt: { update_cache: yes }

- name: Installation outils Cybersécurité
  apt:
    name: [nmap, tcpdump, netcat-openbsd, git, vim, python3, python3-pip, john, ufw]
    state: present

- name: Installation outils Python sécurité
  pip:
    name: [scapy, pwntools]
    executable: pip3
